version: "3.3"
services:
  alice:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add busybox-extras && tail -f /dev/null"
    container_name: alice
    networks:
      ALICE_NET:
        ipv4_address: 10.0.0.2
  bob:
    image: alpine
    command: ash -c "apk update && apk upgrade && apk add busybox-extras && tail -f /dev/null"
    container_name: bob
    networks:
      BOB_NET:
        ipv4_address: 10.1.0.2

networks:
  ALICE_NET:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  BOB_NET:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
